package com.olsh4u.epam.controllers.command;

/**
 * Enumeration of commands which the application supports.
 */
public enum CommandName {
    INDEX,
    SHOW,
    REGISTRATION,
    LOGIN,
    SEARCH,
    LOGOUT,
    MY_ALIEN,
    LIKED,
    RATING,
    PROFILE,
    LANGUAGE,
    WRONG_REQUEST,
    ADMIN_ALIEN,
    ADMIN_SOURCE,
    ADMIN_ABILITY,
    ADMIN_PLANET,
    ADMIN_USER,
    SAVE_ALIEN,
    ADD_USER,
    SAVE_SOURCE,
    SAVE_PLANET,
    CHANGE_PASSWORD,
    CHANGE_ACCESS_RIGHTS,
    SAVE_COMMENT,
    DELETE_SOURCE,
    DELETE_ALIEN,
    SAVE_ABILITY,
    DELETE_ABILITY,
    DELETE_PLANET,
    DELETE_COMMENT,
    CHANGE_AVATAR,
    WATCH_ALIEN,
    STOP_WATCH_ALIEN,
    LIKE,
    DISLIKE,
    ERROR,
}
